---

- name: Converge
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Setup SSH key pairs
      openssh_keypair:
        path: "{{ item }}"
        size: 2048
      register: setup_ssh_keys_result
      loop:
        - /root/test_id_ssh_rsa1
        - /root/test_id_ssh_rsa2

    - include_role:
        name: amtega.authorized_keys
