---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Setup packages
      ansible.builtin.package:
        name: openssh
        state: present

    - name: Setup testing user
      ansible.builtin.user:
        name: testuser
        comment: Testing user