---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Read root authorized_keys file
      command: cat /root/.ssh/authorized_keys
      changed_when: no
      register: read_root_keys_result

    - name: Read testuser authorized_keys file
      command: cat /home/testuser/.ssh/authorized_keys
      changed_when: no
      register: read_testuser_keys_result

    - name: Check that authorized_keys file contains required pairs
      assert:
        that:
          - read_root_keys_result.stdout is search("Test key pair 1")
          - read_root_keys_result.stdout is search("Test key pair 2")
          - read_testuser_keys_result.stdout is search("Test key pair 1")
